# Generated by Django 5.2.6 on 2025-11-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('on leave', 'On Leave'), ('inactive', 'Inactive'), ('deactivated', 'Deactivated')], default='active', max_length=100),
        ),
    ]
