# Generated by Django 5.2.6 on 2025-11-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ImageField(null=True, upload_to='Employee_Pictures'),
        ),
    ]
