# Generated by Django 5.2.6 on 2025-11-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_alter_employee_gender_alter_employee_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='Employee_Pictures'),
        ),
    ]
