# Generated by Django 5.2.6 on 2025-11-03 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_alter_employee_gender_alter_employee_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_lead_team', models.BooleanField(default=False)),
                ('can_supervise', models.BooleanField(default=False)),
                ('can_approve_tasks', models.BooleanField(default=False)),
                ('can_approve_payments', models.BooleanField(default=False)),
                ('can_view_finances', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='cookie',
            name='employee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cookie',
            name='ip',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_1.permission'),
        ),
    ]
