# Generated by Django 5.2.6 on 2025-11-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_permission_cookie_employee_cookie_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='can_assign_tasks',
            field=models.BooleanField(default=False),
        ),
    ]
