# Generated by Django 5.2.6 on 2025-11-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0007_permission_can_assign_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AlterField(
            model_name='project',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
