# Generated by Django 5.2.6 on 2025-11-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0008_remove_team_members_alter_project_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
