# Generated by Django 5.2.6 on 2025-11-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0011_alter_team_members_teamplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='help_text',
        ),
    ]
