# Generated by Django 5.2.6 on 2025-11-06 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0014_alter_task_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('currency', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('daily_limit', models.DecimalField(decimal_places=4, max_digits=10)),
                ('daily_spent', models.DecimalField(decimal_places=4, max_digits=10)),
                ('minimum_balance', models.DecimalField(decimal_places=4, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_frozen', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('owner_company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='app_1.company')),
                ('owner_employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='app_1.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'credit'), ('DEBIT', 'debit')], max_length=30)),
                ('reference', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('before_balance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('after_balance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_1.wallet')),
            ],
        ),
    ]
