# Generated by Django 5.2.6 on 2025-11-06 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0015_notification_wallet_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=4, default='0', max_digits=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='GHC', max_length=50),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='daily_limit',
            field=models.DecimalField(decimal_places=4, default=5000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='daily_spent',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='minimum_balance',
            field=models.DecimalField(decimal_places=4, default=50, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='owner_company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='app_1.company'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='owner_employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='app_1.employee'),
        ),
    ]
