# Generated by Django 5.2.6 on 2025-11-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0016_alter_wallet_balance_alter_wallet_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='owner',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
