# Generated by Django 5.2.6 on 2025-11-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0017_wallet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='chances',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
