# Generated by Django 5.2.6 on 2025-11-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0018_wallet_chances_wallet_is_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='performance',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='can_edit_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(default='Description of the said role'),
        ),
    ]
