# Generated by Django 5.2.6 on 2025-11-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0020_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
