# Generated by Django 5.2.6 on 2025-11-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0022_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='first_login',
            field=models.BooleanField(default=False),
        ),
    ]
