# Generated by Django 5.2.6 on 2025-11-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0023_employee_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
