# Generated by Django 5.2.6 on 2025-11-08 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0024_alter_employee_first_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Folder', max_length=200)),
                ('description', models.TextField(help_text='Description of the folder')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='link',
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(upload_to='Files'),
        ),
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_1.folder'),
        ),
    ]
