# Generated by Django 5.2.6 on 2025-11-08 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0025_folder_remove_file_link_alter_file_path_file_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app_1.company'),
        ),
        migrations.AddField(
            model_name='folder',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='app_1.company'),
        ),
        migrations.AddField(
            model_name='folder',
            name='slug',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
