# Generated by Django 5.2.6 on 2025-11-08 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0028_file_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='project',
        ),
        migrations.AddField(
            model_name='folder',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='app_1.project'),
        ),
    ]
