# Generated by Django 5.2.6 on 2025-11-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0030_file_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
