# Generated by Django 5.2.6 on 2025-11-09 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0031_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='can_edit_projects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_edit_tasks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to='app_1.employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='app_1.employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company', to='app_1.company'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to='app_1.project'),
        ),
    ]
