# Generated by Django 5.2.6 on 2025-11-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0032_permission_can_edit_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='can_use_admin_system',
            field=models.BooleanField(default=False),
        ),
    ]
