# Generated by Django 5.2.6 on 2025-11-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0034_alter_employee_date_of_birth_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='You  have recieved a Message', max_length=200),
        ),
    ]
