# Generated by Django 5.2.6 on 2025-11-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0035_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(default='You  have recieved a Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(default='New Message', max_length=200),
        ),
    ]
