# Generated by Django 5.2.6 on 2025-11-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0036_alter_notification_message_alter_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_name',
            field=models.CharField(default='a', max_length=1000),
            preserve_default=False,
        ),
    ]
