# Generated by Django 5.2.6 on 2025-11-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0039_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='normal', max_length=100),
        ),
    ]
