# Generated by Django 5.2.6 on 2025-11-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0042_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
