# Generated by Django 5.2.6 on 2025-11-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0043_notification_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
