# Generated by Django 5.2.6 on 2025-11-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0044_notification_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_payment_record',
            name='paid_at',
            field=models.DateTimeField(null=True),
        ),
    ]
