# Generated by Django 5.2.6 on 2025-11-13 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0045_alter_task_payment_record_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_payment_record',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_approved_payment_records', to='app_1.employee'),
        ),
    ]
