# Generated by Django 5.2.6 on 2025-11-13 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0046_alter_task_payment_record_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_payment_record',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_created_payment_records', to='app_1.employee'),
        ),
    ]
