# Generated by Django 5.2.6 on 2025-11-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0047_task_payment_record_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='can_join_team',
            field=models.BooleanField(default=False),
        ),
    ]
