# Generated by Django 5.2.6 on 2025-11-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0048_permission_can_join_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
