# Generated by Codex on 2026-03-16

import uuid

from django.db import migrations, models


def _populate_company_uuid(apps, schema_editor):
    Company = apps.get_model("app_1", "Company")
    for company in Company.objects.filter(company_uuid__isnull=True).iterator():
        company.company_uuid = uuid.uuid4()
        company.save(update_fields=["company_uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("app_1", "0049_delete_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="company_uuid",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.RunPython(_populate_company_uuid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="company",
            name="company_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]

