# Generated by Django 5.2.8 on 2025-12-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0050_materials_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment_type',
            name='link',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
