# Generated by Django 5.2.8 on 2025-12-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0051_employment_type_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, help_text='Base Rate for the specified role per task', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(default='Description of the said role', null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='position',
            field=models.CharField(help_text='Position of said employees based on department/company status. Eg. Executive Officer, Department Head, Master, Technician, Helper', max_length=3000, null=True),
        ),
    ]
