# Generated by Django 5.2.8 on 2025-12-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0052_alter_role_base_rate_alter_role_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='performance',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
