# Generated by Django 5.2.8 on 2025-12-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0053_alter_employee_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
