# Generated by Django 5.2.8 on 2026-02-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0054_employee_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('used', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
                ('expiry_date', models.DateTimeField()),
                ('token', models.CharField(max_length=60)),
            ],
        ),
    ]
