# Generated by Django 5.2.8 on 2026-02-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0055_email_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='link',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='password',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
