# Generated by Django 5.2.8 on 2026-02-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0056_company_link_alter_company_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='password',
        ),
        migrations.RemoveField(
            model_name='company',
            name='raw_password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='company',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
