# Generated by Django 5.2.8 on 2026-02-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0057_remove_company_password_remove_company_raw_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_link',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='email_link',
            name='token',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
