# Generated by Django 5.2.8 on 2026-03-01 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0058_alter_email_link_expiry_date_alter_email_link_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_employees', to='app_1.company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_employees', to='app_1.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='father_living_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='father_marital_status',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mother_living_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mother_marital_status',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
