# Generated by Django 5.2.8 on 2026-03-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0060_alter_employee_email_alter_employee_father_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='type',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
