# Generated by Django 5.2.8 on 2026-03-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0061_role_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='name',
        ),
    ]
