# Generated by Django 5.2.8 on 2026-03-11 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0062_remove_role_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='type',
        ),
    ]
