# Generated by Django 5.2.8 on 2026-03-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0063_remove_role_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='type',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
