# Generated by Django 5.2.8 on 2026-03-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0064_role_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='can_create_projects',
            field=models.BooleanField(default=False),
        ),
    ]
