# Generated by Django 5.2.8 on 2026-03-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0065_permission_can_create_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='permission_count',
            field=models.IntegerField(default=0),
        ),
    ]
