# Generated by Django 5.2.8 on 2026-03-16 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0050_company_company_uuid'),
        ('app_1', '0066_permission_permission_count'),
    ]

    operations = [
    ]
