# Generated by Django 5.2.8 on 2026-03-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0067_merge_20260316_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ImageField(blank=True, default='/media/Files/a.webp', null=True, upload_to='Employee_Pictures'),
        ),
    ]
