# Generated by Django 5.2.6 on 2025-11-19 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='userA',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='userB',
        ),
    ]
