# Generated by Django 5.2.6 on 2025-11-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_admin_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='order',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
