# Generated by Django 5.2.6 on 2025-11-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chat_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='mes',
            name='state',
            field=models.CharField(default='not delivered'),
        ),
    ]
