# Generated by Django 5.2.8 on 2025-12-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_mes_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='mes',
            name='type',
            field=models.CharField(default='normal', max_length=300, null=True),
        ),
    ]
