# Generated by Django 5.2.8 on 2025-12-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_mes_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mes',
            name='reply_to',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
