# Generated by Django 5.2.8 on 2026-03-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_mes_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='mes',
            name='state',
            field=models.CharField(default='not delivered', max_length=200),
        ),
    ]
