# Generated by Django 5.2.8 on 2026-03-15 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_1', '0049_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('salary_range', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('application_fields', models.JSONField(blank=True, default=list, help_text="Dynamic application fields as JSON list. Example: [{'key': 'portfolio_url', 'label': 'Portfolio URL', 'type': 'url', 'required': False}]")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='app_1.role')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('resume', models.FileField(upload_to='applicant_uploads/resumes/')),
                ('image', models.FileField(upload_to='applicant_uploads/images/')),
                ('possible_start_date', models.DateField()),
                ('extra_answers', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('employment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='app_1.employment_type')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='job_application.vacancy')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vacancy', 'email'), name='unique_applicant_email_per_vacancy')],
            },
        ),
    ]
