# Generated by Codex on 2026-03-16

import django.db.models.deletion
from django.db import migrations, models


def _backfill_vacancy_company(apps, schema_editor):
    Vacancy = apps.get_model("job_application", "Vacancy")
    for vacancy in Vacancy.objects.filter(company__isnull=True).select_related("role").iterator():
        role = getattr(vacancy, "role", None)
        if role and getattr(role, "company_id", None):
            vacancy.company_id = role.company_id
            vacancy.save(update_fields=["company"])


class Migration(migrations.Migration):
    dependencies = [
        ("app_1", "0050_company_company_uuid"),
        ("job_application", "0002_vacancy_company"),
    ]

    operations = [
        migrations.RunPython(_backfill_vacancy_company, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="vacancy",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacancies",
                to="app_1.company",
            ),
        ),
    ]

