# Generated by Django 5.2.8 on 2026-03-21 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0068_alter_employee_picture'),
        ('job_application', '0003_vacancy_company_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='interview')),
                ('scheduled_for', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job_application.applicant')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_1.employee')),
            ],
        ),
    ]
