# Generated by Django 5.2.8 on 2026-03-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0004_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='type',
        ),
        migrations.AddField(
            model_name='meeting',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
