# Generated by Django 5.2.8 on 2026-03-21 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0068_alter_employee_picture'),
        ('job_application', '0005_remove_meeting_type_meeting_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='job_application.applicant'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='app_1.employee'),
        ),
    ]
