# Generated by Django 5.2.8 on 2026-03-21 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0069_event_task_event'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('job_application', '0006_alter_meeting_applicant_alter_meeting_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='created',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='employee',
        ),
        migrations.AddField(
            model_name='meeting',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_1.event'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='scheduled_for',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='job_application.meeting')),
            ],
        ),
    ]
