# Generated by Django 5.2.8 on 2026-03-21 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0069_event_task_event'),
        ('job_application', '0007_remove_meeting_applicant_remove_meeting_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_1.employee'),
        ),
        migrations.AddField(
            model_name='meetingparticipant',
            name='role',
            field=models.CharField(choices=[('host', 'Host'), ('participant', 'Participant')], default='participant', max_length=20),
        ),
    ]
